# Analise de texto

In [25]:
import spacy
import pandas as pd
from collections import Counter

In [26]:
# Carrega o modelo em português
nlp  = spacy.load('pt_core_news_lg')

# Carrega o texto do arquivo .txt
with open('texto.txt', "r", encoding='utf-8') as arquivo:
    texto = arquivo.read()


# Processa o texto
doc = nlp(texto)

In [27]:
# Lista onde as informações serão armazenadas 
dados = []

# Percorre todos os tokens
for token in doc:

    # Ignora pontuaçõa e espaços
    if token.is_punct or token.is_space:
        continue

    # Armazena as informações na lista
    dados.append({
         'Palavra' : token.text,
        "Lema" : token.lemma_,
        "Classe" : token.pos_,
        "Detalhe" : token.tag_
    })

In [28]:
# Cria o DataFreme com as informaçõaes
df = pd.DataFrame(dados)
df

        Palavra        Lema Classe Detalhe
0             A           o    DET     DET
1       Polícia     Polícia  PROPN   PROPN
2       Federal     Federal  PROPN   PROPN
3     desmontou   desmontar   VERB    VERB
4           uma          um    DET     DET
..          ...         ...    ...     ...
64           na        em o    ADP     ADP
65    apreensão   apreensão   NOUN    NOUN
66           de          de    ADP     ADP
67   documentos   documento   NOUN    NOUN
68  importantes  importante    ADJ     ADJ

[69 rows x 4 columns]

In [29]:
df['Classe'].value_counts()

Classe
NOUN     22
ADP      19
DET       9
VERB      7
PROPN     4
ADJ       4
CCONJ     2
NUM       2
Name: count, dtype: int64

In [30]:
frequencia = Counter(
    token.lemma_.lower()
    for token in doc
    if not token.is_punct
    and not token.is_space
    and not token.is_stop)

df_freq = pd.DataFrame(frequencia.items(), columns=['Palavra', 'Contagem'])
df_freq.sort_values('Contagem', ascending=False).head(20)

         Palavra  Contagem
0        polícia         1
1        federal         1
2      desmontar         1
3      quadrilha         1
4   especializar         1
5         desvio         1
6        remédio         1
7           alto         1
8          custo         1
9         voltar         1
10    tratamento         1
11        câncer         1
12           rio         1
13       janeiro         1
14  investigação         1
15     criminoso         1
16      assaltar         1
17         carga         1
18       estrada         1
19      revender         1